# Copied from https://github.com/satu0king/Github-Documentation-With-Doxygen/blob/master/.github/workflows/main.yml

name: Doxygen Action

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ main, workflow_dispatch ]
  pull_request:
    branches: [ main workflow_dispatch ]


  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
        
    - name: Doxygen Action
      uses: mattnotmitt/doxygen-action@edge
      with:
        # Path to Doxyfile
        doxyfile-path: "./MapWinGIS.doxyfile" # default is ./Doxyfile
        # Working directory
        working-directory: "." # default is .
    
    # - name: Deploy
    #   uses: peaceiris/actions-gh-pages@v3
    #   with:
    #     github_token: ${{ secrets.GITHUB_TOKEN }}
    #     publish_dir: ./html
    
    - name: Publish to GitHub Wiki
      uses: SwiftDocOrg/github-wiki-publish-action@1.0.0
      with:
        path: "./output/html"
      env:
        GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
